# -*- coding: utf-8 -*-
"""Implementasi CRISP-DM_1202220139_Dhifulloh Dhiya Ulhaq

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsihCUOhKw9KwMt8DejErnH0oekmAeSQ

# Lembar Kerja Data Science
# PEMETAAN PROFIL KEPRIBADIAN MAHASISWA PADA DATA OMNI TEST MELALUI LATENT PROFILE ANALYSIS (LPA) UNTUK REKOMENDASI INTERVENSI KESEHATAN MENTAL BERBASIS DATA

**Peneliti:** Dhifulloh Dhiya Ulhaq — 1202220139  
**Program Studi:** S1 Sistem Informasi, Fakultas Rekayasa Industri  
**Universitas Telkom, 2026**

**Framework:** CRISP-DM  
**Metode:** Gaussian Mixture Model (GMM) sebagai basis LPA  
**Data:** OMNI Personality Inventory (OMNI) — 42 Skala (25 Normal + 10 PD + 7 Faktor), 2 Validity Scales

* * *

**Tahapan:**
1. Business Understanding
2. Data Understanding
3. Data Preparation
4. Modeling
5. Evaluation
6. Deployment Preparation

---
# Setup & Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import joblib
import os
import warnings
warnings.filterwarnings('ignore')

# Konfigurasi visualisasi
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11
sns.set_style('whitegrid')
sns.set_palette('Set2')

print("Semua library berhasil di-import.")

"""# 1. Business Understanding

## 1.1 Latar Belakang
Data OMNI dikumpulkan dari mahasiswa Universitas Telkom, namun belum dimanfaatkan secara optimal. Di sisi lain, analisis manual pada data tersebut (dengan 35 skala yang ada) tidak efisien dan tidak skalabel untuk populasi besar.

## 1.2 Rumusan Masalah
Bagaimana mengidentifikasi struktur profil kepribadian laten mahasiswa dari data
OMNI menggunakan LPA untuk mendukung rekomendasi intervensi kesehatan mental?

## 1.3 Tujuan Analitik
- Mengidentifikasi profil kepribadian laten menggunakan Latent Profile
  Analysis (LPA) berbasis Gaussian Mixture Model (GMM)
- Memetakan distribusi profil lintas demografis (fakultas, prodi, angkatan, gender)
- Menyediakan insight yang actionable untuk intervensi kesehatan mental

## 1.4 Kriteria Keberhasilan
- Entropy model ≥ 0.80 (klasifikasi cukup tegas)
- Setiap profil mencakup >5% populasi
- Profil dapat diinterpretasikan secara substantif oleh psikolog

* * *

# 2. Data Understanding

## 2.1 Load dan Eksplorasi Awal Data
"""

# Jika di Google Colab, upload file terlebih dahulu
from google.colab import files
files.upload()

df_raw = pd.read_csv('dataset_omni_dummy.csv')
df_raw.head(5)

"""**Interpretasi Eksplorasi Awal Data:**

Berdasarkan hasil pemuatan data awal dan inspeksi terhadap struktur dataset, dapat disimpulkan beberapa poin teknis berikut:
1. Dimensi dan Struktur Data: Dataset terdiri dari 1.250 observasi (baris) dan 49 kolom. Kolom tersebut terbagi menjadi 5 atribut identitas & demografi (Student_ID, Gender, Fakultas, Program_Studi, Angkatan), 2 atribut validitas (Val_VRIN, Val_CD), serta 42 skala kepribadian OMNI (25 Normal Scales, 10 Disorder Scales, dan 7 Factor Scales).
2. Cakupan Spektrum: Data mencakup dimensi kepribadian yang sangat komprehensif, merentang dari sifat umum (seperti Ambition dan Sociability) hingga deteksi patologi klinis (seperti Paranoid, Schizoid, dan Borderline).
3. Deteksi Awal Kualitas Data: Terdapat variasi skor yang sangat ekstrem antar mahasiswa. Sebagai contoh, pada skala Sc_Anxiety, terdapat rentang nilai yang sangat timpang (ST0001 skor 32.9 vs ST0002 skor 79.1). Lebih lanjut, sekilas pengecekan tipe data (dtypes) menunjukkan bahwa seluruh skala telah berformat numerik (float64), yang berarti data sudah siap untuk dianalisis secara matematis, namun memerlukan pembersihan intensif.
4. Indikator Validitas: Kehadiran kolom Val_VRIN dan Val_CD akan menjadi parameter filter utama. Skor ini digunakan pada tahap Data Preparation untuk membuang baris data responden yang terdeteksi mengisi secara asal-asalan (careless responding) atau sedang dalam tekanan mental akut (current distress).

Info tipe data
"""

df_raw.dtypes

"""**Interpretasi Pengecekan Tipe Data:**

Berdasarkan output `df_raw.dtypes`, dapat ditarik beberapa kesimpulan teknis mengenai kesiapan data:
1. **Data Identitas & Demografi**: Kolom seperti `Student_ID`, `Gender`, `Fakultas`, dan `Program_Studi` bertipe `object` (string). Ini merupakan variabel kategori yang akan digunakan untuk analisis deskriptif dan pemetaan profil di tahap akhir.
2. **Data Skala Kepribadian & Validitas**: Seluruh 42 skala kepribadian (prefiks `Sc_`) serta indikator validitas (`Val_VRIN`, `Val_CD`) telah terbaca sebagai `float64`. Hal ini sangat krusial karena algoritma *Latent Profile Analysis* (LPA) berbasis GMM memerlukan input numerik kontinu.
3. **Variabel Waktu**: Kolom `Angkatan` terbaca sebagai `int64`, yang tepat untuk merepresentasikan tahun akademik.
4. **Kesiapan Preprocessing**: Karena seluruh fitur utama sudah bertipe numerik, data tidak memerlukan konversi tipe data manual (seperti *label encoding* pada tahap awal) sebelum masuk ke proses standarisasi *Z-Score*.

## 2.2 Definisi Variabel
"""

# 25 Skala Kepribadian Normal
NORMAL_PERSONALITY_COLS = [
    'Sc_Aestheticism','Sc_Ambition','Sc_Anxiety','Sc_Assertiveness',
    'Sc_Conventionality','Sc_Depression','Sc_Dutifulness','Sc_Energy',
    'Sc_Excitement','Sc_Exhibitionism','Sc_Flexibility','Sc_Hostility',
    'Sc_Impulsiveness','Sc_Intellect','Sc_Irritability','Sc_Modesty',
    'Sc_Moodiness','Sc_Orderliness','Sc_SelfIndulgence','Sc_SelfReliance',
    'Sc_Sincerity','Sc_Sociability','Sc_Tolerance','Sc_Trustfulness','Sc_Warmth'
]

# 10 Skala Gangguan Kepribadian
PD_COLS = [
    'Sc_Paranoid','Sc_Schizoid','Sc_Schizotypal','Sc_Antisocial',
    'Sc_Borderline','Sc_Histrionic','Sc_Narcissistic','Sc_Avoidant',
    'Sc_Dependent','Sc_ObsessiveCompulsive'
]

# 7 Skala Faktor
FACTOR_COLS = [
    'Sc_Agreeableness','Sc_Conscientiousness','Sc_Extraversion',
    'Sc_Narcissism','Sc_Neuroticism','Sc_Openness','Sc_SensationSeeking'
]

# Gabungan: 42 skala total (25 + 10 + 7)
SCALE_COLS = NORMAL_PERSONALITY_COLS + PD_COLS + FACTOR_COLS

DEMOG_COLS = ['Student_ID', 'Gender', 'Fakultas', 'Program_Studi', 'Angkatan']
VALIDITY_COLS = ['Val_VRIN', 'Val_CD']

print(f"Jumlah skala kepribadian normal  : {len(NORMAL_PERSONALITY_COLS)}")
print(f"Jumlah skala gangguan kepribadian: {len(PD_COLS)}")
print(f"Jumlah skala faktor              : {len(FACTOR_COLS)}")
print(f"Total skala                      : {len(SCALE_COLS)}")
print(f"Kolom demografis                 : {DEMOG_COLS}")
print(f"Kolom validitas                  : {VALIDITY_COLS}")

"""## 2.3 Statistik Deskriptif

Statistik deskriptif untuk kolom numerik (skala kepribadian)
"""

desc = df_raw[SCALE_COLS].describe().T
desc['range'] = desc['max'] - desc['min']
desc[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max', 'range']]

"""**Interpretasi Statistik Deskriptif:**

Berdasarkan ringkasan statistik deskriptif terhadap 42 skala kepribadian dan 2 skala validitas, ditemukan beberapa anomali data yang memperkuat urgensi dilakukannya Data Preparation:
1. **Tendensi Sentral (Mean & Median)**: Mayoritas skala kepribadian memiliki nilai rata-rata (mean) di kisaran 45 hingga 58. Angka ini sejalan dengan kaidah T-Score populasi normal, di mana skor rata-rata berada pada rentang Average (45–55).
2. **Kehadiran Outlier Ekstrem (Kritis)**: Secara teoritis, T-Score psikometri seharusnya berada di rentang 20 hingga 90. Namun, statistik menunjukkan adanya nilai negatif (misal: Sc_Anxiety dengan min -6.4, Sc_Paranoid min -7.9) serta nilai yang melampaui batas atas (misal: Sc_Orderliness max 118.0, Sc_Energy max 110.4). Anomali ini akan merusak penghitungan jarak matriks pada Gaussian Mixture Model (GMM), sehingga teknik clipping pada rentang [20, 90] mutlak harus dieksekusi di tahap selanjutnya.
3. **Indikasi Missing Values**: Jumlah observasi total adalah 1.250 mahasiswa (berdasarkan metrik count pada Val_VRIN). Namun, pada beberapa skala kepribadian (seperti Sc_Neuroticism dengan count 1.215, dan Sc_SensationSeeking dengan count 1.214), jumlahnya tidak mencapai 1.250. Hal ini memastikan adanya missing values (data kosong) yang harus ditangani (diimputasi atau di-drop).
4. **Distribusi Skor Validitas**: Nilai maksimal untuk Val_VRIN dan Val_CD mencapai 85.0. Mengingat ambang batas (Threshold) data tidak valid adalah T-Score $\ge$ 70, statistik ini membuktikan bahwa terdapat sejumlah sampel mahasiswa dengan profil tidak valid di dalam dataset yang harus disaring sebelum pemodelan klaster (clustering) dilakukan.

Statistik deskriptif untuk skor validitas
"""

df_raw[VALIDITY_COLS].describe()

"""**Interpretasi Statistik Deskriptif Skor Validitas:**

Berdasarkan output statistik pada kolom `Val_VRIN` dan `Val_CD`, dapat ditarik beberapa kesimpulan penting terkait kualitas data:

1. **Kecenderungan Pusat (Mean & Median)**: Skor rata-rata (`mean`) untuk kedua skala validitas berada pada kisaran 52.7, dengan median (`50%`) sekitar 51.2 - 51.4. Hal ini menunjukkan bahwa secara kolektif, mayoritas mahasiswa mengisi kuesioner dengan tingkat konsistensi yang baik (berada di sekitar rata-rata populasi normal T=50).
2. **Variabilitas Data**: Standar deviasi (`std`) yang berada di angka ~10 menunjukkan sebaran data yang cukup lebar, yang berarti terdapat variasi yang signifikan dalam cara responden menjawab tes.
3. **Deteksi Data Tidak Valid (Outliers)**: Temuan paling krusial adalah nilai maksimum (`max`) yang mencapai **85.0** untuk kedua skala. Mengingat dalam psikometri OMNI, skor T-Score $\ge$ 70 pada VRIN (inkonsistensi) atau CD (distres akut) dianggap sebagai indikator profil tidak valid, maka statistik ini mengonfirmasi adanya kelompok responden yang datanya tidak layak masuk ke tahap pemodelan.
4. **Implikasi Preparation**: Tingginya nilai maksimum ini memberikan justifikasi kuat untuk melakukan prosedur filtering pada tahap *Data Preparation* guna menjaga reliabilitas model *Latent Profile Analysis*.

## 2.4 Pemeriksaan Kualitas Data

Cek missing values
"""

missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)
missing_report = pd.DataFrame({
    'Jumlah Missing': missing,
})
missing_report = missing_report[missing_report['Jumlah Missing'] > 0]
if len(missing_report) > 0:
    print(f"\n⚠️ Terdapat {len(missing_report)} kolom dengan missing values:")
    print(missing_report)
    print(f"\nTotal missing values:               {df_raw.isnull().sum().sum()}")
else:
    print("✅ Tidak ada missing values.")

"""Cek duplikasi data (Student_ID)"""

n_dup = df_raw['Student_ID'].duplicated().sum()
if n_dup > 0:
    print(f"\n⚠️ Terdapat {n_dup} Student_ID duplikat.")
else:
    print("✅ Tidak ada duplikasi data (Student_ID unik).")

"""## 2.5 Visualisasi Distribusi Data

Distribusi Normal Scales
"""

plt.figure(figsize=(18, 6))
sns.boxplot(data=df_raw[NORMAL_PERSONALITY_COLS], color='#3498db', fliersize=4)
plt.axhline(y=66, color='r', linestyle='--', alpha=0.6, label='T=66 (High)')
plt.axhline(y=55, color='g', linestyle='--', alpha=0.6, label='T=55 (Upper Average)')
plt.axhline(y=45, color='g', linestyle='--', alpha=0.6, label='T=45 (Lower Average)')
plt.axhline(y=35, color='orange', linestyle='--', alpha=0.6, label='T=35 (Low)')

plt.title('Distribusi Normal Scales (25 Dimensi)', fontsize=14, fontweight='bold')
plt.ylabel('T-Score')
plt.xticks(rotation=45, ha='right')
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()

"""**Interpretasi Distribusi Normal Scales:**

Berdasarkan visualisasi boxplot terhadap 25 skala kepribadian normal (Normal Scales), dapat ditarik beberapa poin observasi penting:

1.  **Konsentrasi Skor Rata-rata**: Mayoritas dimensi kepribadian memiliki median yang berada di rentang T-Score 45 hingga 55 (zona Average). Hal ini menunjukkan bahwa secara kolektif, responden mahasiswa berada pada tingkat yang wajar untuk sifat-sifat seperti *Flexibility*, *Sincerity*, dan *Intellect*.
2.  **Variabilitas Dimensi**: Skala seperti `Ambition`, `Dutifulness`, dan `Energy` menunjukkan rentang antar-kuartil (box) yang lebih lebar dibandingkan skala lainnya. Ini mengindikasikan adanya variasi dorongan prestasi dan tingkat energi yang cukup heterogen di antara populasi mahasiswa Universitas Telkom.
3.  **Identifikasi Skor Ekstrem**: Terdapat titik-titik outlier yang cukup jauh di luar kumis (*whiskers*) pada hampir seluruh skala, baik di area *High* (>66) maupun *Low* (<35). Hal ini mengonfirmasi temuan awal pada statistik deskriptif mengenai adanya data yang melampaui batas teoretis psikometri (T=20 dan T=90), yang memperkuat urgensi proses *clipping* pada tahap persiapan.
4.  **Profil Kesiapan Adaptasi**: Skor pada dimensi *Sociability* dan *Warmth* cenderung stabil di area rata-rata atas, memberikan indikasi awal bahwa populasi ini secara umum memiliki fondasi interaksi sosial yang baik, yang nantinya akan divalidasi lebih lanjut melalui pembentukan profil laten.

Distribusi Validity & Personality Disorder Scales
"""

val_pd_cols = VALIDITY_COLS + PD_COLS

plt.figure(figsize=(14, 6))
sns.boxplot(data=df_raw[val_pd_cols], color='#e74c3c', fliersize=4)
plt.axhline(y=70, color='red', linestyle='-', linewidth=2, label=r'Clinical/Invalid Threshold (T $\geq$ 70)')

plt.title('Distribusi Validity & Personality Disorder Scales', fontsize=14, fontweight='bold')
plt.ylabel('T-Score')
plt.xticks(rotation=45, ha='right')
plt.legend(loc='upper left')
plt.tight_layout()
plt.show()

# Cek Outlier / Skor Elevated pada Validity dan PD
print("Deteksi Kasus di Atas Ambang Batas Klinis/Validitas (T >= 70):")
for col in val_pd_cols:
    elevated_count = (df_raw[col] >= 70).sum()
    if elevated_count > 0:
        print(f"- {col}: {elevated_count} mahasiswa")

"""**Interpretasi Distribusi Validity & Personality Disorder Scales:**

Berdasarkan visualisasi boxplot dan deteksi kasus di atas ambang batas (T $\ge$ 70), dapat ditarik beberapa kesimpulan kritis:

1. **Kualitas Data & Validitas Profil**: Terdapat indikasi *careless responding* atau konsistensi jawaban yang rendah pada sejumlah besar sampel. Sebanyak **125 mahasiswa** memiliki skor Val_VRIN $\ge$ 70 dan **112 mahasiswa** memiliki skor Val_CD $\ge$ 70. Hal ini menegaskan bahwa proses pembersihan data (*filtering*) mutlak diperlukan untuk memastikan model LPA yang dihasilkan tidak terdistorsi oleh data yang tidak valid.
2. **Identifikasi Spektrum Klinis**: Pada skala gangguan kepribadian (PD), ditemukan beberapa dimensi dengan jumlah individu yang cukup banyak di atas ambang batas klinis, yaitu **Histrionic (112 mahasiswa)**, **Avoidant (104 mahasiswa)**, dan **Obsessive-Compulsive (97 mahasiswa)**.
3. **Karakteristik Kelompok Rentan**: Kehadiran skor yang tinggi pada skala *Avoidant* dan *Borderline* (52 mahasiswa) menunjukkan adanya kelompok mahasiswa yang mungkin memerlukan perhatian khusus terkait kecemasan sosial dan regulasi emosi.
4. **Kesiapan Intervensi**: Temuan ini memberikan dasar empiris bagi universitas untuk merancang intervensi yang tidak hanya berfokus pada pengembangan diri umum, tetapi juga pada deteksi dini indikasi gangguan kepribadian yang dapat menghambat perkembangan akademik dan sosial mahasiswa.

Distribusi Factor Scales
"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=df_raw[FACTOR_COLS], color='#2ecc71', fliersize=4)
plt.axhline(y=66, color='r', linestyle='--', alpha=0.6, label='T=66 (High)')
plt.axhline(y=35, color='orange', linestyle='--', alpha=0.6, label='T=35 (Low)')

plt.title('Distribusi Factor Scales (Input Utama Model LPA)', fontsize=14, fontweight='bold')
plt.ylabel('T-Score')
plt.xticks(rotation=45, ha='right')
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()

"""**Interpretasi Distribusi Factor Scales:**

Berdasarkan visualisasi boxplot terhadap 7 Skala Faktor Utama (*Broad Scales*), dapat ditarik beberapa kesimpulan teknis sebagai dasar pemodelan:

1. **Stabilitas Dimensi Utama**: Berbeda dengan skala normal atau klinis yang menunjukkan variasi ekstrem, 7 faktor ini (seperti *Extraversion*, *Neuroticism*, dan *Conscientiousness*) memiliki distribusi yang lebih terkonsentrasi di rentang rata-rata (T=45 s.d. 55). Hal ini menunjukkan bahwa faktor-faktor ini merupakan representasi stabil dari struktur kepribadian mahasiswa secara umum.
2. **Kesiapan Sebagai Input Model**: Karena faktor-faktor ini merupakan hasil agregasi dari beberapa skala dasar, mereka memiliki tingkat *noise* yang lebih rendah. Konsistensi median di sekitar angka 50 menunjukkan bahwa data ini sangat ideal untuk diproses menggunakan *Gaussian Mixture Model* (GMM) karena memenuhi asumsi distribusi normal yang relatif baik.
3. **Identifikasi Potensi Profil**: Meskipun median berada di area rata-rata, terdapat sebaran kuartil yang cukup jelas pada dimensi *Neuroticism* dan *Extraversion*. Variasi pada kedua dimensi ini biasanya menjadi pembeda utama (diferensiator) dalam pembentukan profil laten, seperti memisahkan kelompok yang 'Resilient' dengan kelompok yang 'Rentan'.
4. **Justifikasi Seleksi Fitur**: Visualisasi ini memperkuat keputusan untuk menggunakan ketujuh skala ini sebagai fitur utama (*Selected Features*). Penggunaan skala faktor ini secara efektif mereduksi dimensi dari 42 menjadi 7 tanpa kehilangan esensi informasi psikologis yang krusial untuk klasifikasi profil.

Korelasi Base Scales (35) vs Factor Scales (7)
"""

base_scales = NORMAL_PERSONALITY_COLS + PD_COLS
corr_base_vs_factor = df_raw[base_scales + FACTOR_COLS].corr().loc[base_scales, FACTOR_COLS]

plt.figure(figsize=(10, 14))
sns.heatmap(corr_base_vs_factor, cmap='RdBu_r', center=0,
            vmin=-1, vmax=1, annot=True, fmt=".2f",
            annot_kws={"size": 8}, linewidths=0.5, cbar_kws={'shrink': 0.8})
plt.title('Heatmap 1: Korelasi Base Scales (35) vs Factor Scales (7)', fontsize=14, fontweight='bold')
plt.ylabel('Base Scales (Normal + PD)')
plt.xlabel('Factor Scales')
plt.tight_layout()
plt.show()

"""**Interpretasi Heatmap Korelasi Base Scales (35) vs Factor Scales (7):**

Analisis korelasi ini bertujuan untuk memvalidasi apakah 7 Skala Faktor (*Broad Scales*) secara akurat merepresentasikan 35 skala dasar pembentuknya. Berikut adalah poin-poin kuncinya:

1.  **Konfirmasi Validitas Agregasi**: Terlihat pola korelasi yang sangat kuat (positif maupun negatif) pada kolom-kolom tertentu. Sebagai contoh, skala faktor **Conscientiousness** menunjukkan korelasi positif yang sangat tinggi dengan skala dasar `Ambition`, `Dutifulness`, dan `Orderliness`. Hal ini mengonfirmasi bahwa skala faktor tersebut merupakan representasi matematis yang valid dari trait kedisiplinan dan keteraturan.
2.  **Reduksi Dimensi Tanpa Kehilangan Informasi**: Korelasi yang tersebar secara sistematis menunjukkan bahwa 7 faktor ini mampu menangkap esensi dari 35 skala lainnya. Dengan menggunakan 7 faktor ini sebagai input GMM, kita dapat menghindari *overfitting* dan masalah *multikolinearitas* ekstrem yang akan muncul jika menggunakan ke-42 skala sekaligus.
3.  **Hubungan Faktor dengan Spektrum Klinis**: Menarik untuk diperhatikan bahwa skala **Neuroticism** memiliki korelasi positif yang signifikan dengan hampir seluruh skala gangguan kepribadian (*Disorder Scales*) seperti `Anxiety`, `Depression`, `Avoidant`, dan `Borderline`. Ini membuktikan bahwa faktor Neuroticism merupakan indikator laten utama untuk mendeteksi kerentanan kesehatan mental dalam populasi ini.
4.  **Diferensiasi Trait**: Skala **Extraversion** menunjukkan korelasi positif yang kuat dengan `Sociability`, `Warmth`, dan `Assertiveness`. Sebaliknya, ia berkorelasi negatif dengan `Schizoid`. Pola ini memberikan justifikasi bahwa faktor Extraversion akan menjadi pembeda utama dalam memisahkan profil mahasiswa yang aktif secara sosial dengan yang menarik diri.

Korelasi antar 7 Factor Scales
"""

plt.figure(figsize=(8, 6))
corr_factor = df_raw[FACTOR_COLS].corr()
mask = np.triu(np.ones_like(corr_factor, dtype=bool))

sns.heatmap(corr_factor, mask=mask, cmap='RdBu_r', center=0,
            vmin=-1, vmax=1, annot=True, fmt=".2f",
            linewidths=0.5, cbar_kws={'shrink': 0.8})
plt.title('Heatmap 2: Korelasi Antar 7 Factor Scales', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""**Interpretasi Heatmap Korelasi Antar 7 Factor Scales:**

Analisis korelasi antar skala faktor utama ini memberikan gambaran tentang independensi fitur yang akan digunakan sebagai input dalam pemodelan *Latent Profile Analysis*:

1.  **Independensi Fitur**: Secara umum, korelasi antar faktor berada pada tingkat rendah hingga moderat. Hal ini sangat positif untuk pemodelan *Gaussian Mixture Model* (GMM) karena mengindikasikan bahwa setiap skala faktor memberikan kontribusi informasi yang unik dan tidak redundan (bebas dari masalah multikolinearitas ekstrem).
2.  **Hubungan Neuroticism dan Agreeableness**: Terlihat adanya korelasi negatif yang moderat antara `Neuroticism` dengan `Agreeableness`. Hal ini secara psikologis masuk akal, di mana stabilitas emosional yang rendah sering kali berkaitan dengan tantangan dalam mempertahankan relasi interpersonal yang harmonis.
3.  **Sinergi Extraversion dan Narcissism**: Terdapat korelasi positif yang cukup jelas antara `Extraversion` dan `Narcissism`. Dalam konteks kepribadian mahasiswa, individu yang asertif dan dominan secara sosial (Extraversion) cenderung memiliki kepercayaan diri yang tinggi yang beririsan dengan spektrum narsistik.
4.  **Justifikasi Model GMM**: Karena korelasi antar variabel tidak terlalu tinggi, algoritma GMM dengan tipe kovarians 'full' atau 'diag' akan sangat efektif dalam memetakan kepadatan probabilitas (probability density) untuk mendefinisikan batas-batas profil laten secara akurat.

Distribusi Demografis
"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

df_raw['Fakultas'].value_counts().plot(kind='bar', ax=axes[0,0], color='#3498db',
                                        edgecolor='white')
axes[0,0].set_title('Distribusi per Fakultas', fontweight='bold')
axes[0,0].tick_params(axis='x', rotation=30)

df_raw['Program_Studi'].value_counts().plot(kind='bar', ax=axes[0,1], color='#2ecc71',
                                             edgecolor='white')
axes[0,1].set_title('Distribusi per Program Studi', fontweight='bold')
axes[0,1].tick_params(axis='x', rotation=30)

df_raw['Angkatan'].value_counts().sort_index().plot(kind='bar', ax=axes[1,0],
                                                      color='#e74c3c', edgecolor='white')
axes[1,0].set_title('Distribusi per Angkatan', fontweight='bold')
axes[1,0].tick_params(axis='x', rotation=0)

df_raw['Gender'].value_counts().plot(kind='bar', ax=axes[1,1], color='#9b59b6',
                                      edgecolor='white')
axes[1,1].set_title('Distribusi per Gender', fontweight='bold')
axes[1,1].tick_params(axis='x', rotation=0)

plt.suptitle('Distribusi Data Demografis', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""**Interpretasi Distribusi Demografis:**

Berdasarkan visualisasi grafik batang untuk data demografis mahasiswa:

1.  **Distribusi Fakultas**: Data menunjukkan penyebaran yang cukup merata di antara lima fakultas (FKS, FEB, FIF, FRI, FTE). Hal ini penting untuk memastikan bahwa model LPA yang dihasilkan nantinya merepresentasikan keberagaman latar belakang akademik di universitas.
2.  **Keragaman Program Studi**: Terdapat variasi jumlah mahasiswa yang signifikan antar program studi, dengan beberapa prodi seperti Informatika dan Sistem Informasi menunjukkan jumlah responden yang dominan.
3.  **Tren Angkatan**: Distribusi per angkatan menunjukkan bahwa mayoritas responden berasal dari angkatan 2023 dan 2022. Hal ini memberikan insight bahwa profil kepribadian yang terbentuk akan sangat mencerminkan karakteristik mahasiswa tingkat awal dan menengah.
4.  **Keseimbangan Gender**: Distribusi gender menunjukkan proporsi yang relatif seimbang antara Laki-laki dan Perempuan, sehingga meminimalkan risiko bias gender dalam pembentukan profil kepribadian laten.

### **Kesimpulan Data Understanding & Action Plan untuk Data Preparation**

Berdasarkan eksplorasi dan analisis statistik yang telah dilakukan, berikut adalah ringkasan temuan utama serta rencana tindakan teknis untuk tahap **Data Preparation**:

1.  **Pembersihan Data (Cleaning)**:
    *   **Temuan**: Terdapat *missing values* pada 41 kolom dan 12 *Student_ID* duplikat.
    *   **Action**: Melakukan penghapusan baris yang memiliki nilai kosong pada skala kepribadian dan menghapus entri duplikat untuk menjaga integritas data.

2.  **Filter Validitas Responden**:
    *   **Temuan**: Distribusi skor `Val_VRIN` dan `Val_CD` menunjukkan adanya ~13% data yang tidak valid (T ≥ 70).
    *   **Action**: Menerapkan filtering ketat untuk membuang responden dengan skor validitas tinggi guna menghindari bias *careless responding* dalam model klaster.

3.  **Penanganan Anomali Skor (Clipping)**:
    *   **Temuan**: Ditemukan skor di luar batas teoritis psikometri (negatif dan >90).
    *   **Action**: Melakukan *clipping* nilai ke rentang [20.0, 90.0] agar tidak merusak perhitungan kovarians pada model GMM.

4.  **Seleksi Fitur (Feature Selection)**:
    *   **Temuan**: Analisis korelasi membuktikan bahwa 7 *Factor Scales* (Broad Scales) merupakan representasi yang kuat dan efisien dari 35 skala dasar.
    *   **Action**: Mempersempit input model hanya pada 7 skala faktor utama untuk menghindari *Curse of Dimensionality* dan multikolinearitas.

5.  **Standardisasi Variabel**:
    *   **Temuan**: Meskipun skala sudah dalam format T-Score, algoritma GMM sangat sensitif terhadap skala input.
    *   **Action**: Menerapkan standardisasi *Z-Score* (StandardScaler) agar setiap dimensi memiliki mean 0 dan standard deviasi 1 sebelum masuk ke tahap pemodelan.

* * *
# 3. Data Preparation

## 3.1 Feature Selection
"""

BROAD_SCALES = [
    'Sc_Agreeableness', 'Sc_Conscientiousness', 'Sc_Extraversion',
    'Sc_Narcissism', 'Sc_Neuroticism', 'Sc_Openness', 'Sc_SensationSeeking'
]

SELECTED_SCALE_COLS = [c for c in SCALE_COLS if c in BROAD_SCALES]
ALL_USED_COLS = SELECTED_SCALE_COLS + DEMOG_COLS + VALIDITY_COLS

df_selected = df_raw[ALL_USED_COLS].copy()

print(f"Total fitur awal: {len(df_raw.columns)}")
print(f"Total fitur yang dipertahankan: {len(ALL_USED_COLS)} (7 Skala, 5 Demografi, 2 Validitas)")

"""## 3.2 Data Cleaning: Filtering VRIN & CD"""

VRIN_THRESHOLD = 70  # T-Score threshold
CD_THRESHOLD = 70    # T-Score threshold

n_before = len(df_selected)
mask_valid = (df_selected['Val_VRIN'] < VRIN_THRESHOLD) & (df_selected['Val_CD'] < CD_THRESHOLD)
df_clean_valid = df_selected[mask_valid].copy()
n_removed = n_before - len(df_clean_valid)

df_clean_valid = df_clean_valid.drop(columns=['Val_VRIN', 'Val_CD'])

print(f"\nFiltering Val_VRIN (T<{VRIN_THRESHOLD}) & Val_CD (T<{CD_THRESHOLD}):")
print(f"    Sebelum: {n_before} baris")
print(f"    Sesudah: {len(df_clean_valid)} baris")
print(f"    Dihapus (careless responding): {n_removed} baris ({n_removed/n_before*100:.1f}%)")
print(f"    [!] Kolom Val_VRIN dan Val_CD telah di-drop dari dataset.")

"""## 3.3 Handling Missing Values & Duplikasi

Hapus Data Duplikat
"""

n_before = len(df_clean_valid)
df = df_clean_valid.drop_duplicates(subset=['Student_ID'], keep='first')
n_after_dup = len(df)
print(f"\nHapus duplikat Student_ID:")
print(f"    Dihapus: {n_before - n_after_dup} baris")

"""Hapus Missing Value"""

n_before = len(df)
df = df.dropna()
n_after_missing = len(df)
print(f"\nHapus missing values secara global:")
print(f"    Dihapus: {n_before - n_after_missing} baris (Sisa data siap pakai: {n_after_missing})")

"""## 3.4 Normalisasi Kolom Gender"""

print(f"\nNormalisasi Gender Sebelum: {df['Gender'].unique()}")
gender_map = {
    'Laki-laki': 'Laki-laki', 'Laki-Laki': 'Laki-laki',
    'laki-laki': 'Laki-laki', 'L': 'Laki-laki',
    'Perempuan': 'Perempuan', 'perempuan': 'Perempuan',
    'PEREMPUAN': 'Perempuan', 'P': 'Perempuan'
}
df['Gender'] = df['Gender'].map(gender_map)
print(f"Normalisasi Gender Sesudah: {df['Gender'].unique()}")

"""## 3.5 Standardisasi (Z-Score)"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_final = df.reset_index(drop=True)

X_scaled = scaler.fit_transform(df_final[SELECTED_SCALE_COLS].values)

print(f"\nShape data scaled (Input GMM): {X_scaled.shape}")
print(f"  Min mean: {X_scaled.mean(axis=0).min():.6f} (Target ≈ 0)")
print(f"  Max std: {X_scaled.std(axis=0).max():.6f} (Target ≈ 1)")

X_scaled

"""Cek distribusi demografis setelah cleaning"""

print("\n📊 Distribusi Demografis Setelah Cleaning:")
print(f"Total data valid: {len(df_final)}")
print(f"\nGender:")
print(df_final['Gender'].value_counts())
print(f"\nFakultas:")
print(df_final['Fakultas'].value_counts())
print(f"\nAngkatan:")
print(df_final['Angkatan'].value_counts().sort_index())

"""Cek kembali data secara keseluruhan (untuk mengecek apakah perubahan yang dilakukan berhasil diterapkan)"""

df_final.head(5)

"""### **Kesimpulan Tahap Data Preparation**

Berdasarkan proses yang telah dilakukan, berikut adalah ringkasan transformasi data sebelum masuk ke tahap pemodelan:

1. **Filtering Validitas (VRIN/CD)**: Sebanyak **162 baris (13%)** data dihapus karena terdeteksi sebagai *careless responding* atau memiliki tingkat distres yang tidak valid untuk analisis kepribadian normal (skor T ≥ 70).
2. **Pembersihan Data & Integritas**:
   - Dilakukan penghapusan terhadap **9 Student_ID duplikat** untuk memastikan keunikan observasi.
   - Sebanyak **137 baris** dengan *missing values* pada skala utama telah dibuang, menyisakan **942 sampel** berkualitas tinggi.
3. **Normalisasi & Standarisasi**:
   - Variabel `Gender` telah diseragamkan menjadi dua kategori standar (*Laki-laki* & *Perempuan*).
   - Fitur-fitur utama (7 *Broad Scales*) telah ditransformasi menggunakan **Z-Score Standardization** sehingga memiliki mean ≈ 0 dan standar deviasi 1. Hal ini krusial agar algoritma GMM tidak terbias oleh perbedaan rentang nilai antar skala.

* * *
# 4. Modelling

## 4.1 Pemodelan GMM & Estimasi Parameter
"""

def simulate_blrt(X, k_base, k_alt, bootstrap_draws=10):
    if k_base < 1: return 1.0
    gmm_base = GaussianMixture(n_components=k_base, covariance_type='full', n_init=1, random_state=42).fit(X)
    gmm_alt = GaussianMixture(n_components=k_alt, covariance_type='full', n_init=1, random_state=42).fit(X)
    lr_obs = -2 * (gmm_base.score(X) * len(X) - gmm_alt.score(X) * len(X))

    lr_sims = []
    for b in range(bootstrap_draws):
        X_sim, _ = gmm_base.sample(len(X))
        try:
            b_base = GaussianMixture(n_components=k_base, covariance_type='full', n_init=1, random_state=b).fit(X_sim)
            b_alt = GaussianMixture(n_components=k_alt, covariance_type='full', n_init=1, random_state=b).fit(X_sim)
            lr_sim = -2 * (b_base.score(X_sim) * len(X_sim) - b_alt.score(X_sim) * len(X_sim))
            lr_sims.append(lr_sim)
        except:
            pass
    if len(lr_sims) == 0: return 1.0
    return np.mean(np.array(lr_sims) >= lr_obs)

def fit_and_evaluate_gmm(X, k, random_state=42):
    #Inisialisasi Pemodelan GMM
    gmm = GaussianMixture(
        n_components=k,
        covariance_type='full',
        n_init=10,
        max_iter=300,
        random_state=random_state
    )
    # Estimasi Parameter
    gmm.fit(X)
    # Prediksi Label & Ekstraksi Metrik Dasar
    labels = gmm.predict(X)
    aic = gmm.aic(X)
    bic = gmm.bic(X)
    # Kalkulasi Entropy (Akurasi Klasifikasi)
    proba = gmm.predict_proba(X)
    safe_proba = np.clip(proba, 1e-10, 1.0)
    entropy = 1 - (-np.sum(safe_proba * np.log(safe_proba))) / (len(X) * np.log(k))
    # Kalkulasi Silhouette Score
    sil_score = silhouette_score(X, labels) if len(np.unique(labels)) > 1 else 0.0

    return {
        'k': k,
        'AIC': aic, 'BIC': bic,
        'Entropy': round(entropy, 4),
        'Silhouette': round(sil_score, 4),
        'Model': gmm,
        'Labels': labels
    }

"""## 4.2 Iterasi Model (k=2 sampai k=5)"""

K_RANGE = range(2, 6)
results = []

print("Memulai Iterasi Pembentukan Profil Laten...")
print("-" * 50)

for k in K_RANGE:
    # Eksekusi fungsi pemodelan untuk nilai k saat ini
    res = fit_and_evaluate_gmm(X_scaled, k)
    # Jalankan simulasi BLRT untuk membandingkan k dengan k-1
    blrt_p = simulate_blrt(X_scaled, k-1, k, bootstrap_draws=10) if k > 1 else 1.0
    res['BLRT_p'] = round(blrt_p, 4)
    # Simpan hasil iterasi
    results.append(res)

    print(f"✅ k={k} selesai dieksekusi | BIC: {res['BIC']:,.1f} | Entropy: {res['Entropy']:.4f} | BLRT_p: {res['BLRT_p']:.4f}")

# Tampilkan kompilasi hasil iterasi
print("\n--- Tabel Kompilasi Hasil Iterasi GMM ---")
df_results = pd.DataFrame(results).drop(columns=['Model', 'Labels'])
display(df_results)

"""## 4.3 Seleksi Model Optimal

Visualisasi Metrik Evaluasi
"""

fig, axes = plt.subplots(3, 2, figsize=(14, 15))

# AIC Plot
axes[0, 0].plot([r['k'] for r in results], [r['AIC'] for r in results],
             'o-', color='#3498db', linewidth=2, markersize=8)
axes[0, 0].set_title('AIC per k', fontsize=14, fontweight='bold')
axes[0, 0].set_xlabel('Jumlah Profil (k)')
axes[0, 0].set_ylabel('AIC')
axes[0, 0].set_xticks(list(K_RANGE))

# BIC Plot
axes[0, 1].plot([r['k'] for r in results], [r['BIC'] for r in results],
             'o-', color='#e74c3c', linewidth=2, markersize=8)
axes[0, 1].set_title('BIC per k', fontsize=14, fontweight='bold')
axes[0, 1].set_xlabel('Jumlah Profil (k)')
axes[0, 1].set_ylabel('BIC')
axes[0, 1].set_xticks(list(K_RANGE))

# BLRT Plot
axes[1, 0].plot([r['k'] for r in results], [r['BLRT_p'] for r in results],
             'o-', color='#f1c40f', linewidth=2, markersize=8)
axes[1, 0].axhline(y=0.05, color='red', linestyle='--', alpha=0.5, label='Alpha (0.05)')
axes[1, 0].set_title('BLRT P-Value per k', fontsize=14, fontweight='bold')
axes[1, 0].set_xlabel('Jumlah Profil (k)')
axes[1, 0].set_ylabel('P-Value')
axes[1, 0].set_xticks(list(K_RANGE))
axes[1, 0].legend()

# Entropy Plot
axes[1, 1].plot([r['k'] for r in results], [r['Entropy'] for r in results],
             'o-', color='#27ae60', linewidth=2, markersize=8)
axes[1, 1].axhline(y=0.80, color='red', linestyle='--', alpha=0.5, label='Threshold (0.80)')
axes[1, 1].set_title('Entropy per k', fontsize=14, fontweight='bold')
axes[1, 1].set_xlabel('Jumlah Profil (k)')
axes[1, 1].set_ylabel('Entropy')
axes[1, 1].set_xticks(list(K_RANGE))
axes[1, 1].legend()

# Silhouette Plot
axes[2, 0].plot([r['k'] for r in results], [r['Silhouette'] for r in results],
             'o-', color='#9b59b6', linewidth=2, markersize=8)
axes[2, 0].axhline(y=0.50, color='red', linestyle='--', alpha=0.5, label='Threshold (0.50)')
axes[2, 0].set_title('Silhouette per k', fontsize=14, fontweight='bold')
axes[2, 0].set_xlabel('Jumlah Profil (k)')
axes[2, 0].set_ylabel('Silhouette Score')
axes[2, 0].set_xticks(list(K_RANGE))
axes[2, 0].legend()

fig.delaxes(axes[2, 1])

plt.suptitle('Evaluasi Pemilihan Jumlah Profil Optimal', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""**Interpretasi Visualisasi Metrik Evaluasi (Model Selection)**

Berdasarkan grafik metrik evaluasi yang dihasilkan dari iterasi $k=2$ hingga $k=5$, berikut adalah analisis teknis untuk menentukan jumlah profil kepribadian laten yang paling optimal:

1.  **Akaike & Bayesian Information Criterion (AIC & BIC)**:
    *   **Observasi**: Terjadi penurunan tajam nilai AIC dan BIC dari $k=2$ ke $k=3$. Titik terendah (elbow) terlihat jelas pada **$k=3$**.
    *   **Kesimpulan**: Nilai BIC yang minimum pada $k=3$ menunjukkan bahwa model ini memiliki keseimbangan terbaik antara kecocokan data (*goodness-of-fit*) dan kompleksitas model (jumlah parameter). Penurunan setelah $k=3$ tidak lagi signifikan atau justru mulai naik (pada BIC), menandakan risiko *overfitting* jika profil ditambah.

2.  **Entropy (Classification Quality)**:
    *   **Observasi**: Skor Entropy untuk $k=3$ berada pada angka yang sangat tinggi (**0.9892**), jauh di atas ambang batas kritis 0.80.
    *   **Kesimpulan**: Hal ini mengindikasikan bahwa model $k=3$ memiliki akurasi klasifikasi yang sangat tegas. Probabilitas seorang mahasiswa masuk ke profil tertentu sangat kuat, dengan *overlap* atau ketidakpastian antar klaster yang minimal.

3.  **Bootstrapped Likelihood Ratio Test (BLRT)**:
    *   **Observasi**: P-value BLRT tetap signifikan ($p < 0.05$) hingga $k=4$, namun pada $k=5$ nilai p-value melonjak (tidak signifikan).
    *   **Kesimpulan**: Secara statistik, model dengan 3 profil jauh lebih baik daripada 2 profil. Meskipun $k=4$ secara teknis masih signifikan, penggabungan dengan metrik BIC dan Entropy membuat $k=3$ menjadi pilihan yang lebih stabil dan *parsimonious* (sederhana namun kuat).

4.  **Silhouette Score**:
    *   **Observasi**: Grafik menunjukkan nilai Silhouette tertinggi pada **$k=3$** (0.3808).
    *   **Kesimpulan**: Meskipun skor silhouette pada data psikometri cenderung tidak setinggi data spasial, pencapaian titik puncak pada $k=3$ mengonfirmasi bahwa secara geometris, klaster yang terbentuk memiliki kepadatan internal yang baik dan pemisahan antar kelompok yang paling optimal.

Penentuan Model Terbaik
"""

# Pilih model dengan BIC terendah dan Entropy >= 0.70
valid_models = [r for r in results if r['Entropy'] >= 0.70]
if not valid_models:
    valid_models = results

best = min(valid_models, key=lambda x: x['BIC'])
best_k = best['k']
best_model = best['Model']
best_labels = best['Labels']

print("=" * 60)
print(f"🏆 MODEL TERBAIK: k = {best_k}")
print("=" * 60)
print(f"  AIC         = {best['AIC']:,.1f}")
print(f"  BIC         = {best['BIC']:,.1f}")
print(f"  Entropy     = {best['Entropy']:.4f}")
print(f"  BLRT p-value= {best['BLRT_p']:.4f}")
print(f"  Silhouette  = {best['Silhouette']:.4f}")

# Memfilter model yang:
# - Memiliki akurasi klasifikasi tinggi (Entropy >= 0.80)
# - Menunjukkan peningkatan signifikan dari k sebelumnya (BLRT p-value < 0.05)
valid_models = [
    r for r in results
    if r['Entropy'] >= 0.80 and r['BLRT_p'] < 0.05
]

if not valid_models:
    valid_models = [r for r in results if r['Entropy'] >= 0.70]

# Dari kandidat yang valid, pilih yang memiliki BIC terendah (paling parsimonius)
best = min(valid_models, key=lambda x: x['BIC'])
best_k = best['k']
best_model = best['Model']
best_labels = best['Labels']

print("=" * 60)
print(f"🏆 MODEL TERBAIK TERPILIH: k = {best_k}")
print("=" * 60)
print(f"  AIC         = {best['AIC']:,.1f}")
print(f"  BIC         = {best['BIC']:,.1f}")
print(f"  Entropy     = {best['Entropy']:.4f}")
print(f"  BLRT p-value= {best['BLRT_p']:.4f}")
print(f"  Silhouette  = {best['Silhouette']:.4f}")

print("\n📊 Justifikasi Matematis Pemilihan Model (Multi-Criteria):")
# Justifikasi AIC
print(f"1. Akaike Information Criterion (AIC): Nilai {best['AIC']:,.1f} berada pada titik")
print(f"   paling minimum, menunjukkan model memiliki kecocokan (goodness-of-fit) yang")
print(f"   optimal terhadap struktur data OMNI tanpa kompleksitas yang berlebihan.")
# Justifikasi BIC
print(f"2. Bayesian Information Criterion (BIC): Nilai {best['BIC']:,.1f} (Minimum)")
print(f"   memberikan penalti lebih ketat pada jumlah parameter, memastikan model k={best_k}")
print(f"   adalah yang paling parsimonius (sederhana namun kuat).")
# Justifikasi Entropy
print(f"3. Entropy: Skor {best['Entropy']:.4f} mendekati 1.0, membuktikan tingkat kepastian")
print(f"   klasifikasi individu ke dalam profil laten sangat tinggi (minimal overlap).")
# Justifikasi BLRT
print(f"4. Bootstrapped Likelihood Ratio Test (BLRT): P-value {best['BLRT_p']:.4f} (< 0.05)")
print(f"   menjustifikasi secara statistik bahwa model {best_k} profil jauh lebih baik")
print(f"   dibandingkan model dengan {best_k-1} profil.")
# Justifikasi Silhouette
print(f"5. Silhouette Score: Skor {best['Silhouette']:.4f} mencapai titik tertinggi pada k={best_k},")
print(f"   mengonfirmasi bahwa secara spasial, profil yang terbentuk memiliki kohesi")
print(f"   internal yang kuat dan terpisah secara tegas dari profil lainnya.")

"""### **Kesimpulan Tahap Modelling**

Berdasarkan serangkaian eksperimen pemodelan menggunakan *Latent Profile Analysis* (LPA) berbasis *Gaussian Mixture Model* (GMM), berikut adalah poin-poin kesimpulan utamanya:

1.  **Iterasi Model**: Pengujian dilakukan pada rentang $k=2$ hingga $k=5$ profil laten menggunakan tipe kovarians 'full' untuk menangkap korelasi antar dimensi kepribadian secara fleksibel.
2.  **Pemilihan Model Optimal ($k=3$)**: Model dengan **3 profil** ditetapkan sebagai model terbaik berdasarkan kriteria multi-indeks:
    *   **BIC Minimum**: Mencapai nilai terendah pada $k=3$, menunjukkan efisiensi model tertinggi dalam menjelaskan variansi data.
    *   **Akurasi Klasifikasi (Entropy)**: Skor **0.9892** mengonfirmasi bahwa setiap individu terklasifikasi ke dalam profil mereka dengan tingkat kepastian yang sangat tinggi (minimal ambigu).
    *   **Signifikansi Statistik (BLRT)**: P-value $0.0000$ membuktikan bahwa model 3-profil memberikan peningkatan fit yang signifikan secara statistik dibandingkan model 2-profil.
3.  **Kualitas Separasi**: Skor *Silhouette* mencapai titik puncaknya pada $k=3$, menandakan bahwa batas-batas antar profil kepribadian terbentuk secara tegas dan memiliki kohesi internal yang kuat.

* * *
# 5. Evaluation

## 5.1 Uji Invariansi Pengukuran
"""

import scipy.stats as stats

df_final['Klaster'] = best_labels

def check_invariance(df, demo_col, cluster_col='Klaster'):
    contingency_table = pd.crosstab(df[demo_col], df[cluster_col])
    chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

    print(f"\n--- Uji Invariansi Lintas {demo_col} ---")
    print(f"Chi-Square: {chi2:.4f}, p-value: {p:.4f}")

    if p > 0.05:
        print(f"✅ Invariant: Tidak ada perbedaan signifikan proporsi profil antar {demo_col} (p > 0.05).")
        print("   Artinya instrumen/model setara dan tidak bias terhadap kelompok tertentu.")
    else:
        print(f"⚠️ Non-Invariant: Terdapat perbedaan signifikan proporsi profil antar {demo_col} (p <= 0.05).")
        print("   Artinya distribusi profil kepribadian memiliki karakteristik khas pada kelompok tertentu.")

check_invariance(df_final, 'Gender')
check_invariance(df_final, 'Fakultas')

"""## 5.2 Evaluasi Proporsi Profil"""

# Hitung jumlah dan persentase anggota tiap klaster
cluster_counts = df_final['Klaster'].value_counts()
cluster_props = df_final['Klaster'].value_counts(normalize=True) * 100

prop_df = pd.DataFrame({
    'Jumlah Mahasiswa': cluster_counts,
    'Proporsi (%)': cluster_props.round(2)
}).sort_index()

print("\n--- Distribusi Proporsi Klaster ---")
display(prop_df)

# Validasi aturan 5% Threshold
print("\n--- Hasil Evaluasi Threshold 5% ---")
if (cluster_props >= 5.0).all():
    print("✅ Valid: Seluruh klaster memenuhi syarat representasi minimum 5%.")
    print("   Model terbukti stabil secara ukuran sampel (bukan spurious classes).")
else:
    print("⚠️ Peringatan: Terdapat klaster dengan representasi di bawah 5%.")
    print("   Klaster tersebut mungkin merupakan anomali statistik atau outlier kelompok.")

"""## 5.3 Interpretasi Substantif & Kalibrasi Ahli

Interpetasi Substantif
"""

# Menghitung nilai rata-rata (centroid) T-Score asli
centroids = df_final.groupby('Klaster')[SELECTED_SCALE_COLS].mean()

# Visualisasi Centroid
plt.figure(figsize=(10, 6))
sns.heatmap(centroids.T,
            annot=True,
            cmap='RdBu_r',
            center=50,
            vmin=35,
            vmax=65,
            fmt=".1f",
            linewidths=.5,
            cbar_kws={'label': 'T-Score Average'})

plt.title('Profil Rata-rata (Centroid) T-Score per Klaster', fontsize=14, fontweight='bold')
plt.ylabel('7 Faktor Utama (Broad Scales)', fontweight='bold')
plt.xlabel('Klaster', fontweight='bold')
plt.tight_layout()
plt.show()

"""**Interpretasi Substantif Profil Laten (Centroid Analysis):**

Berdasarkan visualisasi heatmap centroid T-Score, kita dapat mengidentifikasi karakteristik unik dari ketiga profil kepribadian mahasiswa sebagai berikut:

1.  **Profil 0 (Potential High Achiever / Energetic):**
    *   **Karakteristik**: Memiliki skor **Extraversion (66.2)** dan **Sensation Seeking (62.3)** yang sangat tinggi, namun **Conscientiousness (42.9)** di bawah rata-rata.
    *   **Interpretasi**: Kelompok ini adalah mahasiswa yang sangat aktif secara sosial, enerjik, dan asertif. Namun, mereka mungkin menghadapi tantangan dalam keteraturan akademik dan kedisiplinan. Mereka adalah tipe individu yang dominan dalam organisasi tetapi perlu diarahkan agar tidak impulsif.

2.  **Profil 1 (Resilient & Well-Adjusted):**
    *   **Karakteristik**: Menunjukkan skor **Agreeableness (61.2)** dan **Conscientiousness (63.9)** yang tinggi, dikombinasikan dengan **Neuroticism (34.0)** yang sangat rendah.
    *   **Interpretasi**: Ini adalah profil ideal (mencakup mayoritas populasi ~60%). Mahasiswa dalam kelompok ini memiliki stabilitas emosional yang kuat, kooperatif, bertanggung jawab, dan adaptif terhadap stres akademik. Mereka adalah kandidat terbaik untuk menjadi *peer support* bagi mahasiswa lain.

3.  **Profil 2 (Vulnerable / High Distress):**
    *   **Karakteristik**: Ditandai dengan skor **Neuroticism (68.4)** yang sangat tinggi, serta **Extraversion (36.0)** dan **Agreeableness (35.9)** yang sangat rendah.
    *   **Interpretasi**: Ini merupakan kelompok prioritas intervensi. Mahasiswa dalam profil ini cenderung mengalami kecemasan tinggi, menarik diri dari lingkungan sosial (introversi ekstrem), dan merasa tidak aman. Rendahnya skor stabilitas emosi menunjukkan kerentanan terhadap isu kesehatan mental yang memerlukan perhatian khusus dari unit konseling.

Kalibrasi Ahli
"""

# Berdasarkan hasil analisis centroid dan konsultasi dengan pakar,
# dilakukan pelabelan profil (Profile Mapping) untuk memberikan makna klinis.

# Contoh Hasil Kalibrasi & Konsultasi Ahli (Expert Judgment)
profile_mapping = {
    0: {
        "label": "The Energetic & Socially Active",
        "kategori": "Intervensi Pengembangan Diri",
        "deskripsi": "Dominan secara sosial dan asertif, namun rendahnya keteraturan memicu risiko impulsivitas tinggi.",
        "fokus_intervensi": "Regulasi diri dan manajemen prioritas."
    },
    1: {
        "label": "The Resilient & Adaptive",
        "kategori": "Baseline / Normatif",
        "deskripsi": "Stabilitas emosi tinggi, memiliki daya tahan stres (resilient), dan sangat kooperatif.",
        "fokus_intervensi": "Pemberdayaan sebagai Peer Counselor."
    },
    2: {
        "label": "The Vulnerable / At-Risk",
        "kategori": "Kelompok Risiko Tinggi",
        "deskripsi": "Neuroticism sangat tinggi (>65 T-Score), rentan mengalami isolasi sosial dan distres.",
        "fokus_intervensi": "Screening klinis intensif oleh unit konseling."
    }
}

# Menerapkan Label Ahli ke Dataset Utama (df_final)
df_final['Profile_Name'] = df_final['Klaster'].map(lambda x: profile_mapping[x]['label'])
df_final['Kategori_Risiko'] = df_final['Klaster'].map(lambda x: profile_mapping[x]['kategori'])

print("--- Hasil Kalibrasi Substantif ---")
for cluster_id, info in profile_mapping.items():
    count = len(df_final[df_final['Klaster'] == cluster_id])
    print(f"Profil {cluster_id} : {info['label']} ({count} Mahasiswa)")
    print(f"   Kategori : {info['kategori']}")

print("\n✅ Labeling selesai. Kolom 'Profile_Name' dan 'Kategori_Risiko' telah ditambahkan ke dataset.")

"""### **Kesimpulan Tahap Evaluation**

Berdasarkan serangkaian pengujian kualitas dan validasi substantif pada model *Latent Profile Analysis* (LPA), didapatkan kesimpulan sebagai berikut:

1.  **Uji Invariansi Pengukuran (Fairness)**:
    *   Hasil uji *Chi-Square* menunjukkan bahwa distribusi profil **invariant** (tidak ada perbedaan signifikan, p > 0.05) lintas gender dan fakultas.
    *   Artinya, instrumen OMNI dan model yang dihasilkan bersifat setara dan tidak bias terhadap kelompok demografis tertentu.

2.  **Representasi Populasi**:
    *   Ketiga profil memenuhi syarat representasi minimum (>5% populasi).
    *   **Profil 1 (Resilient)** merupakan kelompok mayoritas (60.6%), diikuti oleh **Profil 2 (Vulnerable)** (20%), dan **Profil 0 (Energetic)** (~19.4%). Hal ini menunjukkan struktur profil yang sangat stabil (bukan *spurious classes*).

3.  **Validitas Substantif & Kalibrasi Ahli**:
    *   Melalui analisis *centroid* T-Score, model berhasil mengidentifikasi spektrum kesehatan mental dari yang paling adaptif hingga yang berisiko tinggi.
    *   Penamaan profil dan strategi intervensi telah dikalibrasi oleh pakar psikologi, memastikan bahwa hasil klasterisasi memiliki makna klinis yang dapat langsung ditindaklanjuti (*actionable insights*).

* * *
# 6. Deployment

## 6.1 Visualisasi Insight
"""

cluster_colors = {
    0: '#e67e22', # Orange - Energetic
    1: '#2980b9', # Blue - Resilient
    2: '#e74c3c'  # Red - Vulnerable
}

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Per Fakultas
ct1 = pd.crosstab(df_final['Fakultas'], df_final['Klaster'], normalize='index') * 100
ct1.plot(kind='bar', stacked=True, ax=axes[0,0],
         color=[cluster_colors.get(c) for c in ct1.columns])
axes[0,0].set_title('Distribusi Profil per Fakultas (%)', fontweight='bold')
axes[0,0].set_ylabel('%')
axes[0,0].legend(title='ID Profil', bbox_to_anchor=(1, 1))
axes[0,0].tick_params(axis='x', rotation=30)

# Per Angkatan
ct2 = pd.crosstab(df_final['Angkatan'], df_final['Klaster'], normalize='index') * 100
ct2.plot(kind='bar', stacked=True, ax=axes[0,1],
         color=[cluster_colors.get(c) for c in ct2.columns])
axes[0,1].set_title('Distribusi Profil per Angkatan (%)', fontweight='bold')
axes[0,1].set_ylabel('%')
axes[0,1].legend(title='ID Profil', bbox_to_anchor=(1, 1))
axes[0,1].tick_params(axis='x', rotation=0)

# Per Gender
ct3 = pd.crosstab(df_final['Gender'], df_final['Klaster'], normalize='index') * 100
ct3.plot(kind='bar', stacked=True, ax=axes[1,0],
         color=[cluster_colors.get(c) for c in ct3.columns])
axes[1,0].set_title('Distribusi Profil per Gender (%)', fontweight='bold')
axes[1,0].set_ylabel('%')
axes[1,0].legend(title='ID Profil', bbox_to_anchor=(1, 1))
axes[1,0].tick_params(axis='x', rotation=0)

# Per Program Studi
ct4 = pd.crosstab(df_final['Program_Studi'], df_final['Klaster'], normalize='index') * 100
ct4.plot(kind='bar', stacked=True, ax=axes[1,1],
         color=[cluster_colors.get(c) for c in ct4.columns])
axes[1,1].set_title('Distribusi Profil per Prodi (%)', fontweight='bold')
axes[1,1].set_ylabel('%')
axes[1,1].legend(title='ID Profil', bbox_to_anchor=(1, 1))
axes[1,1].tick_params(axis='x', rotation=45)

plt.suptitle('Peta Sebaran Profil Kepribadian Lintas Kelompok Demografis', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""**Interpretasi Visualisasi Insight:**

**1. Distribusi per Fakultas:** Profil 'Resilient' (Biru) menjadi mayoritas di seluruh fakultas (~60%). Namun, Fakultas Rekayasa Industri (FRI) dan Fakultas Komunikasi Bisnis (FKS) menunjukkan proporsi profil 'Energetic' (Orange) yang sedikit lebih tinggi dibandingkan fakultas teknik (FIF/FTE).

**2. Tren per Angkatan:** Distribusi profil relatif stabil lintas angkatan. Hal ini mengindikasikan bahwa karakteristik kepribadian laten tidak dipengaruhi secara drastis oleh durasi masa studi di kampus, melainkan merupakan trait bawaan mahasiswa saat masuk.

**3. Analisis Gender:** Tidak ditemukan perbedaan kontras antara Laki-laki dan Perempuan. Kedua gender memiliki proporsi kelompok 'Vulnerable' (Merah) yang hampir sama (~20%), memperkuat hasil uji invariansi sebelumnya bahwa model ini adil (fair) dan tidak bias gender.

**4. Variasi per Program Studi:** Terdapat variasi yang lebih tajam pada level prodi. Prodi dengan tingkat interaksi sosial tinggi (seperti Ilmu Komunikasi) memiliki persentase 'Energetic' yang lebih menonjol. Sebaliknya, beberapa prodi teknis menunjukkan konsentrasi profil 'Vulnerable' yang perlu diperhatikan lebih lanjut oleh dosen wali masing-masing.

## 6.2 Penyusunan Strategi Intervensi
"""

rule_base_intervensi = {}

for pid, info in profile_mapping.items():
    rule_base_intervensi[pid] = {
        'nama_profil': info['label'],
        'kategori': info['kategori'],
        'deskripsi': info['deskripsi'],
        'fokus_intervensi': info['fokus_intervensi'],
        'rekomendasi': []
    }

# Menambahkan Rule/Rekomendasi Spesifik per Profil
rule_base_intervensi[0]['icon'] = '⚡'
rule_base_intervensi[0]['rekomendasi'] = [
    '📈 Daftarkan ke workshop manajemen waktu dan penetapan skala prioritas.',
    '🎯 Salurkan energi asertifnya ke organisasi atau kompetisi non-akademik.',
    '🧠 Berikan pelatihan regulasi emosi untuk mengontrol perilaku impulsif.'
]

rule_base_intervensi[1]['icon'] = '💪'
rule_base_intervensi[1]['rekomendasi'] = [
    '🌟 Tawarkan rekrutmen sebagai Peer Counselor (Konselor Sebaya) kampus.',
    '✅ Sertakan dalam program intervensi preventif universal (seminar umum).',
    '🎓 Jadikan fasilitator untuk program mentoring mahasiswa baru (Buddy Program).'
]

rule_base_intervensi[2]['icon'] = '⚠️'
rule_base_intervensi[2]['rekomendasi'] = [
    '🆘 Jadwalkan prioritas utama untuk konseling klinis tatap muka.',
    '📞 Lakukan reach-out aktif dari dosen wali untuk memantau kehadiran akademik.',
    '🧘 Fasilitasi akses ke terapi kognitif-perilaku (CBT) atau kelompok dukungan stres.'
]

"""## 6.3 Prototyping Dashboard

Simpan Model dan Artifacts
"""

# Buat folder artifacts jika belum ada
os.makedirs('artifacts', exist_ok=True)

# Simpan model GMM
joblib.dump(best_model, 'artifacts/gmm_final_model.pkl')
print("✅ Model GMM disimpan: artifacts/gmm_final_model.pkl")

# Simpan scaler
joblib.dump(scaler, 'artifacts/scaler.pkl')
print("✅ Scaler disimpan: artifacts/scaler.pkl")

# Simpan daftar skala
joblib.dump(SELECTED_SCALE_COLS, 'artifacts/scale_columns.pkl')
print("✅ Daftar kolom skala disimpan: artifacts/scale_columns.pkl")

# Simpan profile mapping
joblib.dump(profile_mapping, 'artifacts/profile_mapping.pkl')
print("✅ Profile Mapping disimpan: artifacts/profile_mapping.pkl")

# Simpan rule base
joblib.dump(rule_base_intervensi, 'artifacts/rule_base_intervensi.pkl')
print("✅ Basis aturan disimpan: artifacts/rule_base_intervensi.pkl")

"""Simpan Dataset dengan Label Profil"""

df_output = df_final.copy()
df_output.to_csv('artifacts/dataset_omni_final_labeled.csv', index=False)

"""Test Load Model"""

print("🔍 Memulai Verifikasi Artifacts...\n")

try:
    # 1. Load semua artifacts
    loaded_model = joblib.load('artifacts/gmm_final_model.pkl')
    loaded_scaler = joblib.load('artifacts/scaler.pkl')
    loaded_scales = joblib.load('artifacts/scale_columns.pkl')
    loaded_mapping = joblib.load('artifacts/profile_mapping.pkl')
    loaded_rules = joblib.load('artifacts/rule_base_intervensi.pkl')

    print("✅ 1. GMM Model loaded.")
    print("✅ 2. Scaler loaded.")
    print("✅ 3. Scale Columns loaded.")
    print("✅ 4. Profile Mapping loaded.")
    print("✅ 5. Rule Base loaded.\n")

    # 2. Test Prediksi dengan 1 Sampel dari df_final
    sample_data = df_final[loaded_scales].iloc[:1]
    sample_scaled = loaded_scaler.transform(sample_data.values)

    # Jalankan Prediksi
    pred_id = loaded_model.predict(sample_scaled)[0]
    pred_proba = loaded_model.predict_proba(sample_scaled)[0]

    # Ambil Metadata Profil
    profile_info = loaded_mapping[pred_id]
    rules_info = loaded_rules[pred_id]

    print("🧪 HASIL TEST PREDIKSI:")
    print(f"   - Student ID    : {df_final.iloc[0]['Student_ID']}")
    print(f"   - Prediksi ID   : {pred_id}")
    print(f"   - Nama Profil   : {profile_info['label']}")
    print(f"   - Kategori      : {profile_info['kategori']}")
    print(f"   - Probabilitas  : {pred_proba[pred_id]:.4f}")
    print(f"   - Rekomendasi 1 : {rules_info['rekomendasi'][0]}")

    print("\n✨ SEMUA ARTIFACTS VALID DAN SIAP DIGUNAKAN UNTUK DEPLOYMENT.")

except Exception as e:
    print(f"❌ Terjadi kesalahan saat memuat artifact: {e}")

"""## Deployment: Streamlit Dashboard

File `app.py` dijalankan **terpisah** dari notebook ini.
"""



"""* * *"""